name: 'Dokploy Compose Deploy'
description: 'Build, push Docker image; update compose file; deploy via Dokploy; cleanup'
branding:
  icon: "upload-cloud"
  color: "blue"
  
inputs:
  dokploy_domain:
    description: 'Dokploy panel domain'
    required: true
  api_key:
    description: 'API key for Dokploy'
    required: true
  compose_id:
    description: 'Compose ID in Dokploy'
    required: true
  registry_domain:
    description: 'Docker registry domain (leave empty for DockerHub/local)'
    required: false
    default: ""
  registry_username:
    description: 'Docker registry username'
    required: false
  registry_token:
    description: 'Docker registry password/token'
    required: false
  image_name:
    description: 'Image name (repository/name)'
    required: true
  tag:
    description: 'Tag for the image'
    required: false
    default: 'latest'
  dockerfile_path:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  context_path:
    description: 'Build context directory (defaults to Dockerfile folder)'
    required: false
    default: ""
  compose_path:
    description: 'Path to docker-compose.yml'
    required: false
    default: 'docker-compose.yml'
  do_clean:
    description: 'Whether to run cleanAll after deploy'
    required: false
    default: 'false'

outputs:
  deployment_id:
    description: 'Deployment ID from Dokploy'
  status:
    description: 'Deployment status'
  logs:
    description: 'Deployment logs'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine build context
      id: prepare
      run: |
        if [ -z "${{ inputs.context_path }}" ]; then
          CONTEXT_DIR=$(dirname "${{ inputs.dockerfile_path }}")
        else
          CONTEXT_DIR="${{ inputs.context_path }}"
        fi
        echo "context_dir=$CONTEXT_DIR" >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to Docker registry
      if: inputs.registry_username != '' && inputs.registry_token != ''
      run: |
        echo "ðŸ” Logging in to Docker registry..."
        echo "${{ inputs.registry_token }}" | docker login ${{ inputs.registry_domain }} -u ${{ inputs.registry_username }} --password-stdin
      shell: bash

    - name: Build and push image
      run: |
        echo "ðŸš€ Building image..."
        IMAGE_TAG="${{ inputs.image_name }}:${{ inputs.tag }}"
        if [ -n "${{ inputs.registry_domain }}" ]; then
          IMAGE="${{ inputs.registry_domain }}/$IMAGE_TAG"
        else
          IMAGE="$IMAGE_TAG"
        fi

        docker build -f "${{ inputs.dockerfile_path }}" -t "$IMAGE" "${{ steps.prepare.outputs.context_dir }}"
        docker push "$IMAGE" || echo "âš ï¸ No registry configured or push failed, continuing..."
      shell: bash

    - name: Update Compose file locally
      run: |
        echo "ðŸ”§ Updating docker-compose.yml..."
        if [ -n "${{ inputs.registry_domain }}" ]; then
          IMAGE="${{ inputs.registry_domain }}/${{ inputs.image_name }}:${{ inputs.tag }}"
        else
          IMAGE="${{ inputs.image_name }}:${{ inputs.tag }}"
        fi

        if command -v yq >/dev/null 2>&1; then
          echo "ðŸ›  Using yq for precise update..."
          yq e "(.services[] | select(.image | contains(\"${{ inputs.image_name }}\"))).image = \"$IMAGE\"" -i ${{ inputs.compose_path }}
          cp ${{ inputs.compose_path }} composed.tmp.yml
        else
          echo "âš ï¸ yq not found, falling back to sed..."
          sed "s|image:.*${{ inputs.image_name }}.*|image: $IMAGE|" ${{ inputs.compose_path }} > composed.tmp.yml
        fi
      shell: bash

    - name: Update Compose in Dokploy
      run: |
        echo "ðŸ“¤ Sending updated compose to Dokploy..."
        PAYLOAD=$(jq -Rs . < composed.tmp.yml)
        curl -s -X POST "https://${{ inputs.dokploy_domain }}/api/compose/update" \
          -H "x-api-key: ${{ inputs.api_key }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"composeId\": \"${{ inputs.compose_id }}\",
                \"composeFile\": $PAYLOAD
              }"
      shell: bash

    - name: Trigger Deploy
      run: |
        echo "ðŸš€ Triggering deployment..."
        curl -s -X POST "https://${{ inputs.dokploy_domain }}/api/compose/deploy" \
          -H "x-api-key: ${{ inputs.api_key }}" \
          -H "Content-Type: application/json" \
          -d "{\"composeId\": \"${{ inputs.compose_id }}\"}"
      shell: bash

    - name: Clean if requested
      if: ${{ inputs.do_clean == 'true' }}
      run: |
        echo "ðŸ§¹ Running cleanup..."
        curl -s -X POST "https://${{ inputs.dokploy_domain }}/api/settings/cleanAll" \
          -H "x-api-key: ${{ inputs.api_key }}" \
          -H "Content-Type: application/json"
      shell: bash
